---
- hosts: all
  sudo: yes
  tasks:
    - yum: pkg=libselinux-python state=installed
    - yum: pkg=epel-release state=installed
    - yum: pkg=libselinux-python state=installed
    - yum: pkg=python-meld3 state=installed
    - yum: pkg=rubygems state=installed
    - yum: pkg=git state=installed
    - yum: pkg=gcc state=installed
    - yum: pkg=patch state=installed
    - yum: pkg=openssl-devel state=installed
    - yum: pkg=http://dev.mysql.com/get/mysql-community-release-el6-5.noarch.rpm
    - yum: pkg=mysql-community-devel state=installed
    - yum: pkg=libcurl state=installed
    - yum: pkg=libcurl-devel state=installed
    - yum: pkg=bison state=installed
    - yum: pkg=bison-devel state=installed
    - yum: pkg=libjpeg-turbo state=installed
    - yum: pkg=libjpeg-turbo-devel state=installed
    - yum: pkg=libpng state=installed
    - yum: pkg=libpng-devel state=installed
    - yum: pkg=libmcrypt state=installed
    - yum: pkg=libmcrypt-devel state=installed
    - yum: pkg=readline state=installed
    - yum: pkg=readline-devel state=installed
    - yum: pkg=libtidy state=installed
    - yum: pkg=libtidy-devel state=installed
    - yum: pkg=autoconf state=installed
    - yum: pkg=automake state=installed
    - yum: pkg=libxml2-devel state=installed
    - yum: pkg=libxslt-devel state=installed
