---
- hosts: all
  sudo: yes
  tasks:
    - user: name=isucon groups=wheel
    - lineinfile: dest=/etc/sudoers state=present regexp='^%wheel ALL\=' line='%wheel ALL=(ALL) NOPASSWD:ALL' validate='visudo -cf %s'
    - command: yum update -y
    - yum: pkg=http://nginx.org/packages/old/centos/6/x86_64/nginx-1.6.1-1.el6.ngx.x86_64.rpm
    - service: name=nginx enabled=true
    - yum: pkg=mysql-community-server state=installed
    - service: name=mysqld state=running enabled=true
    - yum: pkg=MySQL-python state=installed
    - yum: pkg=git state=installed
    - git: repo=https://github.com/isucon/isucon4.git dest=/tmp/isucon4
    - shell: cp /tmp/isucon4/qualifier/ami/files/nginx.conf /etc/nginx/nginx.conf
      notify:
        - reload nginx
    - shell: cp /tmp/isucon4/qualifier/ami/files/nginx.php.conf /etc/nginx/nginx.php.conf
    - name: copy my.cnf
      shell: cp /tmp/isucon4/qualifier/ami/files/my.cnf /etc/my.cnf
      notify:
        - restart mysqld
    - command: rm -rf /tmp/isucon
      args:
        removes: /tmp/isucon
    - file: path=/tmp/isucon state=directory 
    - shell: rsync -a /tmp/isucon4/qualifier/sql /tmp/isucon/
    - shell: rsync -a /tmp/isucon4/qualifier/webapp /tmp/isucon/
    - shell: |
        cp /tmp/isucon4/qualifier/init.sh /tmp/isucon/init.sh
        chmod a+x /tmp/isucon/init.sh
    - shell: |
        cp /tmp/isucon4/qualifier/ami/files/env.sh /tmp/isucon/env.sh
        chmod a+x /tmp/isucon/env.sh
    - shell: |
        cp /tmp/isucon4/qualifier/ami/files/bashrc /home/isucon/.bashrc
        chmod a+x /home/isucon/.bashrc
    - command: chown -R isucon:isucon /tmp/isucon
    - command: rsync -avz --delete --exclude-from=/tmp/isucon4/qualifier/ami/files/rsync_exclude.txt /tmp/isucon/ /home/isucon/
      sudo: yes
  post_tasks:
    - command: ./init.sh
      sudo_user: isucon
      args:
        chdir: /home/isucon
    - mysql_user: name=isucon password=isucon priv=*.*:ALL state=present
  handlers:
    - name: restart mysqld
      action: service name=mysqld state=restarted
    - name: reload nginx
      action: service name=nginx state=restarted
