---
- hosts: all
  sudo_user: isucon
  sudo: yes
  tasks:
    - command: git clone https://github.com/tagomoris/xbuild.git /home/isucon/.xbuild
      args:
        creates: /home/isucon/.xbuild/ruby-install

    # ruby
    - command: /home/isucon/.xbuild/ruby-install 2.1.3 /home/isucon/.local/ruby
      args:
        creates: /home/isucon/.local/ruby/bin/ruby
    - command: /home/isucon/env.sh gem install --no-rdoc --no-ri foreman
      args:
        creates: /home/isucon/.local/ruby/bin/foreman
    - command: /home/isucon/env.sh bundle install
      args:
        chdir: /home/isucon/webapp/ruby
    # node
    - command: /home/isucon/.xbuild/node-install v0.10.31 /home/isucon/.local/node
      args:
        creates: /home/isucon/.local/node/bin/node
    - command: /home/isucon/env.sh npm install
      args:
        chdir: /home/isucon/webapp/node
    # python
    - command: /home/isucon/.xbuild/python-install 2.7.8 /home/isucon/.local/python
      args:
        creates: /home/isucon/.local/python/bin/python
    - command: /home/isucon/env.sh pip install gunicorn Flask MySQL-python
      args:
        creates: /home/isucon/.local/python/bin/gunicorn
    # perl
    - shell: /home/isucon/.xbuild/perl-install 5.20.0 /home/isucon/.local/perl; test -x /home/isucon/.local/perl/bin/perl
      args:
        creates: /home/isucon/.local/perl/bin/perl
    - command: /home/isucon/env.sh carton install
      args:
        chdir: /home/isucon/webapp/perl

    # php
    - command: /home/isucon/.xbuild/php-install 5.6.0 /home/isucon/.local/php
      args:
        creates: /home/isucon/.local/php/bin/php
    - shell: |
        cp /tmp/isucon4/qualifier/ami/files/php.ini /home/isucon/.local/php/etc/php.ini
        chown isucon:isucon /home/isucon/.local/php/etc/php.ini
