---
- hosts: all
  sudo: yes
  tasks:
    - command: rm -rf /tmp/benchmarker
      args:
        removes: /tmp/benchmarker
    - shell: rsync -aL --delete /tmp/isucon4/qualifier/benchmarker /tmp/
    - command: chown -R isucon:isucon /tmp/benchmarker
    - lineinfile: dest=/tmp/benchmarker/Makefile state=present regexp='^GIT_COMMIT=.*' line='GIT_COMMIT=""'
    - lineinfile: dest=/tmp/benchmarker/main.go state=present regexp='checkInstanceMetadata\(\)' line=''
    - name: build benchmarker
      command: /home/isucon/env.sh make release
      sudo_user: isucon
      args:
        chdir: /tmp/benchmarker
    - command: mv /tmp/benchmarker/benchmarker /home/isucon/
      sudo_user: isucon
